spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/osteria_brillante
spring.datasource.username=postgres
spring.datasource.password=1234
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Cole o valor gerado abaixo
api.security.token.secret=Z2VtaW5pLWFwaS1zZWN1cmUtb3N0ZXJpYS1icmlsaGFudGUtMDk4NzY1NDMyMTAxMjM0NTY3ODkwYWJjZGVmZ2hpajEwMjM0NTY3ODkwYWJjZGVmZ2hpag==